# Generated by Django 4.1.9 on 2023-07-06 20:13

import os
from django.db import migrations


def fixtures(apps, schema_editor):
    if os.environ.get('DOCKER'):
        Entity = apps.get_model("sampleapp", "Entity")
        for i in range(100):
            Entity.objects.create(sentence=f'This is number {i}', output='x')


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0001_initial'),
    ]

    operations = [
            migrations.RunPython(fixtures)
    ]
