# Generated by Django 4.1.9 on 2023-07-13 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0002_test_fixtures'),
    ]

    operations = [
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ent', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=100)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sampleapp.entity')),
            ],
        ),
    ]
