# Generated by Django 4.1.9 on 2023-07-06 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0003_segment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='output',
            field=models.JSONField(blank=True, db_column='output', default='[]'),
        ),
    ]
