# Generated by Django 4.1.9 on 2023-07-13 19:27

from django.db import migrations


def migrate(apps, schema_editor):
    Entity = apps.get_model("sampleapp", "Entity")
    Segment = apps.get_model("sampleapp", "Segment")
    for entity in Entity.objects.all():
        for segment in entity.output:
            Segment.objects.create(entity=entity, ent=segment['ent'], label=segment['label'])


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0003_segment'),
    ]

    operations = [
        migrations.RunPython(code=migrate, reverse_code=backwards),
    ]
