# Generated by Django 4.1.9 on 2023-07-13 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0004_migrate_output_to_segments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='output',
        ),
    ]
