# Generated by Django 4.1.9 on 2023-07-06 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0004_alter_entity_output'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entity',
            old_name='output',
            new_name='legacy_output',
        ),
    ]
